<?php

/**
 * Class FieldtypeFontIconPicker
 *
 * @author			: İskender TOTOĞLU, @ukyo (community), @trk (Github)
 * @website			: http://altivebir.com.tr
 * @projectWebsite	: https://github.com/trk/FieldtypeFontIconPicker
 */
class FieldtypeFontIconPicker extends Fieldtype {

	public static function getModuleInfo() {
		return array(
			'title' => 'FieldtypeFontIconPicker',
			'summary' => __('Allow you to use icon picker input field.'),
			'version' => 3,
			'author' => 'İskender TOTOĞLU | @ukyo(community), @trk (Github), http://altivebir.com.tr',
			'icon' => 'flag-o',
			'href' => 'https://github.com/trk/FieldtypeFontIconPicker',
			'installs' => [
				'InputfieldFontIconPicker',
				'MarkupFontIconPicker'
			],
		);
	}

	public function init() {
		parent::init();

		// Load FontIconPicker Base CSS File
		wire('config')->styles->append(wire('config')->urls->FieldtypeFontIconPicker . "Libraries/fontIconPicker-2.0.0/css/jquery.fonticonpicker.css");

		// Load FontIconPicker Themes CSS Files
		wire('config')->styles->append(wire('config')->urls->FieldtypeFontIconPicker . "Libraries/fontIconPicker-2.0.0/themes/grey-theme/jquery.fonticonpicker.grey.min.css");
		wire('config')->styles->append(wire('config')->urls->FieldtypeFontIconPicker . "Libraries/fontIconPicker-2.0.0/themes/dark-grey-theme/jquery.fonticonpicker.darkgrey.min.css");
		wire('config')->styles->append(wire('config')->urls->FieldtypeFontIconPicker . "Libraries/fontIconPicker-2.0.0/themes/bootstrap-theme/jquery.fonticonpicker.bootstrap.min.css");
		wire('config')->styles->append(wire('config')->urls->FieldtypeFontIconPicker . "Libraries/fontIconPicker-2.0.0/themes/inverted-theme/jquery.fonticonpicker.inverted.min.css");

		// Load FontIconPicker Base JS File
		wire('config')->scripts->append(wire('config')->urls->FieldtypeFontIconPicker . "Libraries/fontIconPicker-2.0.0/jquery.fonticonpicker.min.js");
	}

	/**
	 * Return the associated InputfieldFontIconPicker
	 *
	 */
	public function getInputfield(Page $page, Field $field) {
		$inputField = $this->modules->get('InputfieldFontIconPicker');
		return $inputField;
	}

	/**
	 * Sanitize value for storage
	 */
	public function sanitizeValue(Page $page, Field $field, $value) {
		$value = str_replace(wire('modules')->get('InputfieldFontIconPicker')->attr('prefix'), '', $value);
		return $value;
	}

	/**
	 * Return the database schema in specified format
	 *
	 */
	public function getDatabaseSchema(Field $field) {

		// get the default schema
		$schema = parent::getDatabaseSchema($field);

		$schema['data'] = "VARCHAR(255) NOT NULL DEFAULT ''";

		return $schema;
	}
}