<?php

/**
 * Class InputfieldFontIconPicker
 *
 * @author			: İskender TOTOĞLU, @ukyo (community), @trk (Github)
 * @website			: http://altivebir.com.tr
 * @projectWebsite	: https://github.com/trk/FieldtypeFontIconPicker
 */
class InputfieldFontIconPicker extends Inputfield {
	protected $attributes = array();

	public static function getModuleInfo() {
		return array(
			'title' => 'InputfieldFontIconPicker',
			'summary' => __('Font icon picker input for fieldtype font icon picker, allow you to select font-awesome icons'),
			'version' => 8,
			'author' => 'İskender TOTOĞLU | @ukyo(community), @trk (Github), http://altivebir.com.tr',
			'href' => 'https://github.com/trk/FieldtypeFontIconPicker',
			'icon' => 'flag',
			'requires' => array(
				'FieldtypeFontIconPicker',
            )
		);
	}

	public function __construct() {
		parent::__construct();
		$this->setAttribute('class', 'AvbIconPicker');
		$this->setAttribute('prefix', 'fa fa-');
		$this->setAttribute('category', '');
		$this->setAttribute('theme', 'fip-grey');
		$this->setAttribute('empty-icon', 1);
		$this->setAttribute('empty-icon-value', '');
		$this->setAttribute('icons-per-page', 20);
		$this->setAttribute('has-search', 1);
	}

	/**
	 * Init
	 */
	public function init() {
		parent::init();
		$this->attributes = $this->getAttributes();
		$conf = $this->getModuleInfo();
		$version = (int) $conf['version'];
		$libraryUrl = "{$this->config->urls->FieldtypeFontIconPicker}Libraries/fontIconPicker-2.0.0/";

		// Load Main Css File
		$this->config->styles->add("{$libraryUrl}css/jquery.fonticonpicker.css?v={$version}");
		/**
		 * Load Themes if Needed
		 *
		 * fip-grey : The default theme
		 * fip-darkgrey : A deeper shade of the grey theme
		 * fip-bootstrap : A nice icon picker theme
		 * fip-inverted : Inverted color scheme
		 */
		$this->config->styles->add("{$libraryUrl}themes/grey-theme/jquery.fonticonpicker.grey.min.css?v={$version}");
		$this->config->styles->add("{$libraryUrl}themes/dark-grey-theme/jquery.fonticonpicker.darkgrey.min.css?v={$version}");
		$this->config->styles->add("{$libraryUrl}themes/bootstrap-theme/jquery.fonticonpicker.bootstrap.min.css?v={$version}");
		$this->config->styles->add("{$libraryUrl}themes/inverted-theme/jquery.fonticonpicker.inverted.min.css?v={$version}");

		// Load Main Js File
		$this->config->scripts->add("{$libraryUrl}jquery.fonticonpicker.js?v={$version}");
	}

	/**
	 * Get Attributes
	 *
	 * @return array
	 */
	public function getAttributes() {
		$attrs = parent::getAttributes();
		return $attrs;
	}

	public function setAttribute($key, $value) {
		return parent::setAttribute($key, $value);
	}

	/**
	 * Rende InputfieldFontIconPicker
	 *
	 * @return string
	 */
	public function ___render() {
		// Set Prefixed Value
		if($this->attr('value')) $this->setAttribute('value', $this->attr('prefix') . $this->attr('value'));

		// Set check theme is empty?
		if($this->attr('theme') == '') $this->setAttribute('theme', 'fip-grey');

		if($this->attr('icons-per-page') < 1) $this->setAttribute('icons-per-page', 20);

		// Set true | false for has-search
		if($this->attr('has-search') === 1) $this->setAttribute('has-search', 'true');
		else  $this->setAttribute('has-search', 'false');

		// Set true | false for empty icon
		if($this->attr('empty-icon') === 1) $this->setAttribute('empty-icon', 'true');
		else  $this->setAttribute('empty-icon', 'false');

		$output = "\n<select " . $this->getAttributesString($this->getAttributes()) . ">
					\n\t<option value=''>" . $this->_('No Icon') . "</option>";

		// Load Icons file as an Array
		include(wire('config')->paths->FieldtypeFontIconPicker . 'Libraries/Icons.php');

		if($this->attr('category') && array_key_exists($this->attr('category'), $FontAwesomeIcons)) {
			$icons[] = $FontAwesomeIcons[$this->attr('category')];
		} else {
			$icons = $FontAwesomeIcons;
		}

		foreach($icons as $key => $categories) {
			if(isset($categories['title'])) {
				$output .= "<optgroup label='{$categories['title']}'>";
				if(isset($categories['icons'])) {
					foreach ($categories['icons'] as $k => $icon) {
						$iconValue = $this->attr('prefix') . $icon;
						$selected = ($this->attr('value') == $iconValue) ? " selected='selected'" : "";
						$output .= "<option value='{$iconValue}'{$selected}>{$iconValue}</option>";
					}
				}
				$output .= "</optgroup>";
			}
		}

		$output .= "</select>";

		return $output;
	}

	public function ___getConfigInputfields() {
		$inputfields = parent::___getConfigInputfields();

		/**
		 * Prefix
		 */
		$field = $this->modules->get('InputfieldText');
		$field->setAttribute('name', 'prefix');
		$field->label = $this->_('Prefix');
		$field->setAttribute('value', $this->attr('prefix'));
		$inputfields->append($field);

		/**
		 * Coregory Select
		 */
		$field = $this->modules->get('InputfieldSelect');
		$field->setAttribute('name', 'category');
		$field->label = __('Category');
		$field->description = __('Select an icon category, if you want a specified category for show.');
		// Load Icons file as an Array
		include(wire('config')->paths->FieldtypeFontIconPicker . 'Libraries/Icons.php');
		foreach($FontAwesomeIcons as $key => $icon) {
			$selected = ($this->attr('category') && $this->attr('category') == $key) ? ['selected' => 'selected'] : [];
			$field->addOption($key, $icon['title'], $selected);
		}
		$inputfields->append($field);

		/**
		 * Theme Select
		 */
		$themes = array(
			'fip-grey' => __('The default theme'),
			'fip-darkgrey' => __('A deeper shade of the grey theme'),
			'fip-bootstrap' => __('A nice icon picker theme'),
			'fip-inverted' => __('Inverted color scheme')
		);

		$field = $this->modules->get('InputfieldSelect');
		$field->setAttribute('name', 'theme');
		$field->label = __('Theme');
		$field->description = __('The theme to be used with the InputfieldFontIconPicker.');
		foreach($themes as $key => $title) {
			$selected = ($this->attr('theme') && $this->attr('theme') == $key) ? ['selected' => 'selected'] : [];
			$field->addOption($key, $title, $selected);
		}
		$inputfields->append($field);

		/**
		 * Empty Icon
		 */
		$field = $this->modules->get('InputfieldRadios');
		$field->setAttribute('name', 'empty-icon');
		$field->label = __('Empty Icon');
		$field->description = __('Whether or not empty icon should be shown on the icon picker. If you give your users the option to pick no icon, then leave it enabled.');
		$field->addOption(1, 'True', ($this->attr('empty-icon')) ? ['selected' => 'selected'] : []);
		$field->addOption(0, 'False', (!$this->attr('empty-icon')) ? ['selected' => 'selected'] : []);
		$inputfields->append($field);

		/**
		 * Empty Icon Value
		 */
		$field = $this->modules->get('InputfieldText');
		$field->setAttribute('name', 'empty-icon-value');
		$field->setAttribute('value', $this->attr('empty-icon-value'));
		$field->label = __('Empty Icon Value');
		$field->description = __('What should be the value of the INPUT or SELECT field when no icon is selected. This is only used when emptyIcon is set to true.');
		$inputfields->append($field);

		/**
		 * Icon Per Page
		 */
		$field = $this->modules->get('InputfieldInteger');
		$field->setAttribute('name', 'icons-per-page');
		$field->label = $this->_('Icon Per Page');
		$field->setAttribute('value', $this->attr('icons-per-page'));
		$field->setAttribute('size', 3);
		$field->description = $this->_('Number of icons per page on the icon picker. Please note that if you have emptyIcon set to true then the actual number will be one less. For better appearance always provide a number in multiple of 5.');
		$inputfields->append($field);

		/**
		 * Has Search
		 */
		$field = $this->modules->get('InputfieldRadios');
		$field->setAttribute('name', 'has-search');
		$field->label = __('Has Search');
		$field->description = __('Whether or not to show the search bar. The search result is always non case sensitive. When the fontIconPicker is initiated on a SELECT element, the option labels (or HTML) are used for search, not the option values.');
		$field->addOption(1, 'True', ($this->attr('has-search')) ? ['selected' => 'selected'] : []);
		$field->addOption(0, 'False', (!$this->attr('has-search')) ? ['selected' => 'selected'] : []);
		$inputfields->add($field);

		return $inputfields;
	}
}