<?php
function InputfieldFontIconPickerIcons() {
    $icons = array(
        'title' => 'FontAwesome',
        'version' => '4.5.0',
        'css' => 'https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css',
        'categorised' => true,
        'prefix' => 'fa fa-',
        'icons' => array(
            'web-application-icons' => array(
                'title' => __('Web Application Icons'),
                'icons' => array(
                    'adjust',
                    'anchor',
                    'archive',
                    'area-chart',
                    'arrows',
                    'arrows-h',
                    'arrows-v',
                    'asterisk',
                    'at',
                    // 'automobile', // (alias)
                    'balance-scale',
                    'ban',
                    // 'bank', // (alias)
                    'bar-chart',
                    // 'bar-chart-o', // (alias)
                    'barcode',
                    'bars',
                    // 'battery-0', // (alias)
                    // 'battery-1', // (alias)
                    // 'battery-2', // (alias)
                    // 'battery-3', // (alias)
                    // 'battery-4', // (alias)
                    'battery-empty',
                    'battery-full',
                    'battery-half',
                    'battery-quarter',
                    'battery-three-quarters',
                    'bed',
                    'beer',
                    'bell',
                    'bell-o',
                    'bell-slash',
                    'bell-slash-o',
                    'bicycle',
                    'binoculars',
                    'birthday-cake',
                    'bluetooth',
                    'bluetooth-b',
                    'bolt',
                    'bomb',
                    'book',
                    'bookmark',
                    'bookmark-o',
                    'briefcase',
                    'bug',
                    'building',
                    'building-o',
                    'bullhorn',
                    'bullseye',
                    'bus',
                    // 'cab', // (alias)
                    'calculator',
                    'calendar',
                    'calendar-check-o',
                    'calendar-minus-o',
                    'calendar-o',
                    'calendar-plus-o',
                    'calendar-times-o',
                    'camera',
                    'camera-retro',
                    'car',
                    'caret-square-o-down',
                    'caret-square-o-left',
                    'caret-square-o-right',
                    'caret-square-o-up',
                    'cart-arrow-down',
                    'cart-plus',
                    'cc',
                    'certificate',
                    'check',
                    'check-circle',
                    'check-circle-o',
                    'check-square',
                    'check-square-o',
                    'child',
                    'circle',
                    'circle-o',
                    'circle-o-notch',
                    'circle-thin',
                    'clock-o',
                    'clone',
                    // 'close', // (alias)
                    'cloud',
                    'cloud-download',
                    'cloud-upload',
                    'code',
                    'code-fork',
                    'coffee',
                    'cog',
                    'cogs',
                    'comment',
                    'comment-o',
                    'commenting',
                    'commenting-o',
                    'comments',
                    'comments-o',
                    'compass',
                    'copyright',
                    'creative-commons',
                    'credit-card',
                    'crop',
                    'crosshairs',
                    'cube',
                    'cubes',
                    'cutlery',
                    // 'dashboard', // (alias)
                    'database',
                    'desktop',
                    'diamond',
                    'dot-circle-o',
                    'download',
                    // 'edit', // (alias)
                    'ellipsis-h',
                    'ellipsis-v',
                    'envelope',
                    'envelope-o',
                    'envelope-square',
                    'eraser',
                    'exchange',
                    'exclamation',
                    'exclamation-circle',
                    'exclamation-triangle',
                    'external-link',
                    'external-link-square',
                    'eye',
                    'eye-slash',
                    'eyedropper',
                    'fax',
                    // 'feed', // (alias)
                    'female',
                    'fighter-jet',
                    'file-archive-o',
                    'file-audio-o',
                    'file-code-o',
                    'file-excel-o',
                    'file-image-o',
                    // 'file-movie-o', // (alias)
                    'file-pdf-o',
                    // 'file-photo-o', // (alias)
                    'file-picture-o', // (alias)
                    'file-powerpoint-o',
                    'file-sound-o', // (alias)
                    'file-video-o',
                    'file-word-o',
                    'file-zip-o', // (alias)
                    'film',
                    'filter',
                    'fire',
                    'fire-extinguisher',
                    'flag',
                    'flag-checkered',
                    'flag-o',
                    // 'flash', // (alias)
                    'flask',
                    'folder',
                    'folder-o',
                    'folder-open',
                    'folder-open-o',
                    'frown-o',
                    'futbol-o',
                    'gamepad',
                    'gavel',
                    // 'gear', // (alias)
                    // 'gears', // (alias)
                    'gift',
                    'glass',
                    'globe',
                    'graduation-cap',
                    // 'group', // (alias)
                    // 'hand-grab-o', // (alias)
                    'hand-lizard-o',
                    'hand-paper-o',
                    'hand-peace-o',
                    'hand-pointer-o',
                    'hand-rock-o',
                    'hand-scissors-o',
                    'hand-spock-o',
                    // 'hand-stop-o', // (alias)
                    'hashtag',
                    'hdd-o',
                    'headphones',
                    'heart',
                    'heart-o',
                    'heartbeat',
                    'history',
                    'home',
                    // 'hotel', // (alias)
                    'hourglass',
                    // 'hourglass-1', // (alias)
                    // 'hourglass-2', // (alias)
                    // 'hourglass-3', //  (alias)
                    'hourglass-end',
                    'hourglass-half',
                    'hourglass-o',
                    'hourglass-start',
                    'i-cursor',
                    // 'image', // (alias)
                    'inbox',
                    'industry',
                    'info',
                    'info-circle',
                    // 'institution', // (alias)
                    'key',
                    'keyboard-o',
                    'language',
                    'laptop',
                    'leaf',
                    // 'legal', // (alias)
                    'lemon-o',
                    'level-down',
                    'level-up',
                    // 'life-bouy', // (alias)
                    // 'life-buoy', // (alias)
                    'life-ring',
                    // 'life-saver', // (alias)
                    'lightbulb-o',
                    'line-chart',
                    'location-arrow',
                    'lock',
                    'magic',
                    'magnet',
                    // 'mail-forward', // (alias)
                    // 'mail-reply', // (alias)
                    // 'mail-reply-all', // (alias)
                    'male',
                    'map',
                    'map-marker',
                    'map-o',
                    'map-pin',
                    'map-signs',
                    'meh-o',
                    'microphone',
                    'microphone-slash',
                    'minus',
                    'minus-circle',
                    'minus-square',
                    'minus-square-o',
                    'mobile',
                    'mobile-phone', //  (alias)
                    'money',
                    'moon-o',
                    'mortar-board', // (alias)
                    'motorcycle',
                    'mouse-pointer',
                    'music',
                    'navicon', // (alias)
                    'newspaper-o',
                    'object-group',
                    'object-ungroup',
                    'paint-brush',
                    'paper-plane',
                    'paper-plane-o',
                    'paw',
                    'pencil',
                    'pencil-square',
                    'pencil-square-o',
                    'percent',
                    'phone',
                    'phone-square',
                    // 'photo', // (alias)
                    'picture-o',
                    'pie-chart',
                    'plane',
                    'plug',
                    'plus',
                    'plus-circle',
                    'plus-square',
                    'plus-square-o',
                    'power-off',
                    'print',
                    'puzzle-piece',
                    'qrcode',
                    'question',
                    'question-circle',
                    'quote-left',
                    'quote-right',
                    'random',
                    'recycle',
                    'refresh',
                    'registered',
                    // 'remove', // (alias)
                    // 'reorder', // (alias)
                    'reply',
                    'reply-all',
                    'retweet',
                    'road',
                    'rocket',
                    'rss',
                    'rss-square',
                    'search',
                    'search-minus',
                    'search-plus',
                    // 'send', // (alias)
                    // 'send-o', // (alias)
                    'server',
                    'share',
                    'share-alt',
                    'share-alt-square',
                    'share-square',
                    'share-square-o',
                    'shield',
                    'ship',
                    'shopping-bag',
                    'shopping-basket',
                    'shopping-cart',
                    'sign-in',
                    'sign-out',
                    'signal',
                    'sitemap',
                    'sliders',
                    'smile-o',
                    // 'soccer-ball-o', // (alias)
                    'sort',
                    'sort-alpha-asc',
                    'sort-alpha-desc',
                    'sort-amount-asc',
                    'sort-amount-desc',
                    'sort-asc',
                    'sort-desc',
                    // 'sort-down', // (alias)
                    'sort-numeric-asc',
                    'sort-numeric-desc',
                    // 'sort-up', // (alias)
                    'space-shuttle',
                    'spinner',
                    'spoon',
                    'square',
                    'square-o',
                    'star',
                    'star-half',
                    // 'star-half-empty', // (alias)
                    // 'star-half-full', // (alias)
                    'star-half-o',
                    'star-o',
                    'sticky-note',
                    'sticky-note-o',
                    'street-view',
                    'suitcase',
                    'sun-o',
                    // 'support', // (alias)
                    'tablet',
                    'tachometer',
                    'tag',
                    'tags',
                    'tasks',
                    'taxi',
                    'television',
                    'terminal',
                    'thumb-tack',
                    'thumbs-down',
                    'thumbs-o-down',
                    'thumbs-o-up',
                    'thumbs-up',
                    'ticket',
                    'times',
                    'times-circle',
                    'times-circle-o',
                    'tint',
                    // 'toggle-down', // (alias)
                    // 'toggle-left', // (alias)
                    'toggle-off',
                    'toggle-on',
                    // 'toggle-right', // (alias)
                    // 'toggle-up', // (alias)
                    'trademark',
                    'trash',
                    'trash-o',
                    'tree',
                    'trophy',
                    'truck',
                    'tty',
                    // 'tv', // (alias)
                    'umbrella',
                    'university',
                    'unlock',
                    'unlock-alt',
                    'unsorted', // (alias)
                    'upload',
                    'user',
                    'user-plus',
                    'user-secret',
                    'user-times',
                    'users',
                    'video-camera',
                    'volume-down',
                    'volume-off',
                    'volume-up',
                    // 'warning', // (alias)
                    'wheelchair',
                    'wifi',
                    'wrench'
                )
            ),
            'hand-icons' => array(
                'title' => __('Hand Icons'),
                'icons' => array(
                    // 'hand-grab-o', // (alias)
                    'hand-lizard-o',
                    'hand-o-down',
                    'hand-o-left',
                    'hand-o-right',
                    'hand-o-up',
                    'hand-paper-o',
                    'hand-peace-o',
                    'hand-pointer-o',
                    'hand-rock-o',
                    'hand-scissors-o',
                    'hand-spock-o',
                    // 'hand-stop-o', // (alias)
                    'thumbs-down',
                    'thumbs-o-down',
                    'thumbs-o-up',
                    'thumbs-up'
                )
            ),
            'transportation-icons' => array(
                'title' => __('Transportation Icons'),
                'icons' => array(
                    'ambulance',
                    // 'automobile', // (alias)
                    'bicycle',
                    'bus',
                    // 'cab', // (alias)
                    'car',
                    'fighter-jet',
                    'motorcycle',
                    'plane',
                    'rocket',
                    'ship',
                    'space-shuttle',
                    'subway',
                    'taxi',
                    'train',
                    'truck',
                    'wheelchair'
                )
            ),
            'gender-icons' => array(
                'title' => __('Gender Icons'),
                'icons' => array(
                    'genderless',
                    // 'intersex', // (alias)
                    'mars',
                    'mars-double',
                    'mars-stroke',
                    'mars-stroke-h',
                    'mars-stroke-v',
                    'mercury',
                    'neuter',
                    'transgender',
                    'transgender-alt',
                    'venus',
                    'venus-double',
                    'venus-mars',
                )
            ),
            'file-type-icons' => array(
                'title' => __('File Type Icons'),
                'icons' => array(
                    'file',
                    'file-archive-o',
                    'file-audio-o',
                    'file-code-o',
                    'file-excel-o',
                    'file-image-o',
                    // 'file-movie-o', // (alias)
                    'file-o',
                    'file-pdf-o',
                    // 'file-photo-o', // (alias)
                    // 'file-picture-o', // (alias)
                    'file-powerpoint-o',
                    // 'file-sound-o', // (alias)
                    'file-text',
                    'file-text-o',
                    'file-video-o',
                    'file-word-o',
                    // 'file-zip-o', // (alias)
                )
            ),
            'spinner-icons' => array(
                'title' => __('Spinner Icons'),
                'icons' => array(
                    'circle-o-notch',
                    'cog',
                    // 'gear', // (alias)
                    'refresh',
                    'spinner'
                )
            ),
            'form-control-icons' => array(
                'title' => __('Form Control Icons'),
                'icons' => array(
                    'check-square',
                    'check-square-o',
                    'circle',
                    'circle-o',
                    'dot-circle-o',
                    'minus-square',
                    'minus-square-o',
                    'plus-square',
                    'plus-square-o',
                    'square',
                    'square-o'
                )
            ),
            'payment-icons' => array(
                'title' => __('Payment Icons'),
                'icons' => array(
                    'cc-amex',
                    'cc-diners-club',
                    'cc-discover',
                    'cc-jcb',
                    'cc-mastercard',
                    'cc-paypal',
                    'cc-stripe',
                    'cc-visa',
                    'credit-card',
                    'credit-card-alt',
                    'google-wallet',
                    'paypal'
                )
            ),
            'chart-icons' => array(
                'title' => __('Chart Icons'),
                'icons' => array(
                    'area-chart',
                    'bar-chart',
                    // 'bar-chart-o', //  (alias)
                    'line-chart',
                    'pie-chart'
                )
            ),
            'currency-icons' => array(
                'title' => __('Currency Icons'),
                'icons' => array(
                    // 'bitcoin', // (alias)
                    'btc',
                    // 'cny', // (alias)
                    // 'dollar', // (alias)
                    'eur',
                    // 'euro', // (alias)
                    'gbp',
                    'gg',
                    'gg-circle',
                    'ils',
                    'inr',
                    'jpy',
                    'krw',
                    'money',
                    // 'rmb', // (alias)
                    // 'rouble', // (alias)
                    'rub',
                    // 'ruble', // (alias)
                    // 'rupee', //  (alias)
                    // 'shekel', // (alias)
                    // 'sheqel', // (alias)
                    'try',
                    // 'turkish-lira', // (alias)
                    'usd',
                    // 'won', // (alias)
                    // 'yen', // (alias)
                )
            ),
            'text-editor-icons' => array(
                'title' => __('Text Editor Icons'),
                'icons' => array(
                    'align-center',
                    'align-justify',
                    'align-left',
                    'align-right',
                    'bold',
                    // 'chain', // (alias)
                    'chain-broken',
                    'clipboard',
                    'columns',
                    // 'copy', // (alias)
                    // 'cut', // (alias)
                    // 'dedent', // (alias)
                    'eraser',
                    'file',
                    'file-o',
                    'file-text',
                    'file-text-o',
                    'files-o',
                    'floppy-o',
                    'font',
                    'header',
                    'indent',
                    'italic',
                    'link',
                    'list',
                    'list-alt',
                    'list-ol',
                    'list-ul',
                    'outdent',
                    'paperclip',
                    'paragraph',
                    // 'paste', // (alias)
                    'repeat',
                    // 'rotate-left', // (alias)
                    // 'rotate-right', // (alias)
                    // 'save', // (alias)
                    'scissors',
                    'strikethrough',
                    'subscript',
                    'superscript',
                    'table',
                    'text-height',
                    'text-width',
                    'th',
                    'th-large',
                    'th-list',
                    'underline',
                    'undo',
                    // 'unlink' // (alias)
                )
            ),
            'directional-icons' => array(
                'title' => __('Directional Icons'),
                'icons' => array(
                    'angle-double-down',
                    'angle-double-left',
                    'angle-double-right',
                    'angle-double-up',
                    'angle-down',
                    'angle-left',
                    'angle-right',
                    'angle-up',
                    'arrow-circle-down',
                    'arrow-circle-left',
                    'arrow-circle-o-down',
                    'arrow-circle-o-left',
                    'arrow-circle-o-right',
                    'arrow-circle-o-up',
                    'arrow-circle-right',
                    'arrow-circle-up',
                    'arrow-down',
                    'arrow-left',
                    'arrow-right',
                    'arrow-up',
                    'arrows',
                    'arrows-alt',
                    'arrows-h',
                    'arrows-v',
                    'caret-down',
                    'caret-left',
                    'caret-right',
                    'caret-square-o-down',
                    'caret-square-o-left',
                    'caret-square-o-right',
                    'caret-square-o-up',
                    'caret-up',
                    'chevron-circle-down',
                    'chevron-circle-left',
                    'chevron-circle-right',
                    'chevron-circle-up',
                    'chevron-down',
                    'chevron-left',
                    'chevron-right',
                    'chevron-up',
                    'exchange',
                    'hand-o-down',
                    'hand-o-left',
                    'hand-o-right',
                    'hand-o-up',
                    'long-arrow-down',
                    'long-arrow-left',
                    'long-arrow-right',
                    'long-arrow-up',
                    // 'toggle-down', // (alias)
                    // 'toggle-left', // (alias)
                    // 'toggle-right', // (alias)
                    // 'toggle-up' // (alias)
                )
            ),
            'video-player-icons' => array(
                'title' => __('Video Player Icons'),
                'icons' => array(
                    'arrows-alt',
                    'backward',
                    'compress',
                    'eject',
                    'expand',
                    'fast-backward',
                    'fast-forward',
                    'forward',
                    'pause',
                    'pause-circle',
                    'pause-circle-o',
                    'play',
                    'play-circle',
                    'play-circle-o',
                    'random',
                    'step-backward',
                    'step-forward',
                    'stop',
                    'stop-circle',
                    'stop-circle-o',
                    'youtube-play'
                )
            ),
            'brand-icons' => array(
                'title' => __('Brand Icons'),
                'icons' => array(
                    '500px',
                    'adn',
                    'amazon',
                    'android',
                    'angellist',
                    'apple',
                    'behance',
                    'behance-square',
                    'bitbucket',
                    'bitbucket-square',
                    // 'bitcoin', // (alias)
                    'black-tie',
                    'bluetooth',
                    'bluetooth-b',
                    'btc',
                    'buysellads',
                    'cc-amex',
                    'cc-diners-club',
                    'cc-discover',
                    'cc-jcb',
                    'cc-mastercard',
                    'cc-paypal',
                    'cc-stripe',
                    'cc-visa',
                    'chrome',
                    'codepen',
                    'codiepie',
                    'connectdevelop',
                    'contao',
                    'credit-card-alt',
                    'css3',
                    'dashcube',
                    'delicious',
                    'deviantart',
                    'digg',
                    'dribbble',
                    'dropbox',
                    'drupal',
                    'edge',
                    'empire',
                    'expeditedssl',
                    'facebook',
                    // 'facebook-f', // (alias)
                    'facebook-official',
                    'facebook-square',
                    'firefox',
                    'flickr',
                    'fonticons',
                    'fort-awesome',
                    'forumbee',
                    'foursquare',
                    // 'ge', // (alias)
                    'get-pocket',
                    'gg',
                    'gg-circle',
                    'git',
                    'git-square',
                    'github',
                    'github-alt',
                    'github-square',
                    // 'gittip', // (alias)
                    'google',
                    'google-plus',
                    'google-plus-square',
                    'google-wallet',
                    'gratipay',
                    'hacker-news',
                    'houzz',
                    'html5',
                    'instagram',
                    'internet-explorer',
                    'ioxhost',
                    'joomla',
                    'jsfiddle',
                    'lastfm',
                    'lastfm-square',
                    'leanpub',
                    'linkedin',
                    'linkedin-square',
                    'linux',
                    'maxcdn',
                    'meanpath',
                    'medium',
                    'mixcloud',
                    'modx',
                    'odnoklassniki',
                    'odnoklassniki-square',
                    'opencart',
                    'openid',
                    'opera',
                    'optin-monster',
                    'pagelines',
                    'paypal',
                    'pied-piper',
                    'pied-piper-alt',
                    'pinterest',
                    'pinterest-p',
                    'pinterest-square',
                    'product-hunt',
                    'qq',
                    // 'ra', // (alias)
                    'rebel',
                    'reddit',
                    'reddit-alien',
                    'reddit-square',
                    'renren',
                    'safari',
                    'scribd',
                    'sellsy',
                    'share-alt',
                    'share-alt-square',
                    'shirtsinbulk',
                    'simplybuilt',
                    'skyatlas',
                    'skype',
                    'slack',
                    'slideshare',
                    'soundcloud',
                    'spotify',
                    'stack-exchange',
                    'stack-overflow',
                    'steam',
                    'steam-square',
                    'stumbleupon',
                    'stumbleupon-circle',
                    'tencent-weibo',
                    'trello',
                    'tripadvisor',
                    'tumblr',
                    'tumblr-square',
                    'twitch',
                    'twitter',
                    'twitter-square',
                    'usb',
                    'viacoin',
                    'vimeo',
                    'vimeo-square',
                    'vine',
                    'vk',
                    // 'wechat', // (alias)
                    'weibo',
                    'weixin',
                    'whatsapp',
                    'wikipedia-w',
                    'windows',
                    'wordpress',
                    'xing',
                    'xing-square',
                    'y-combinator',
                    // 'y-combinator-square', // (alias)
                    'yahoo',
                    // 'yc', // (alias)
                    // 'yc-square', // (alias)
                    'yelp',
                    'youtube',
                    'youtube-play',
                    'youtube-square'
                )
            ),
            'medical-icons' => array(
                'title' => __('Medical Icons'),
                'icons' => array(
                    'ambulance',
                    'h-square',
                    'heart',
                    'heart-o',
                    'heartbeat',
                    'hospital-o',
                    'medkit',
                    'plus-square',
                    'stethoscope',
                    'user-md',
                    'wheelchair'
                )
            )
        )
    );

    return $icons;
}