<?php
function InputfieldFontIconPickerFontAwesome5() {
    $icons = array(
        'title' => 'FontAwesome5',
        'version' => '5.0.12',
        "stylesheet" => '<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">',
        'categorised' => true,
        'attributes' => array(),
        'icons' => array(

            "accessibility" => array(
                "title" => __("Accessibility", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "accessible-icon",
                    "american-sign-language-interpreting",
                    "assistive-listening-systems",
                    "audio-description",
                    "blind",
                    "braille",
                    "closed-captioning",
                    "deaf",
                    "low-vision",
                    "phone-volume",
                    "question-circle",
                    "sign-language",
                    "tty",
                    "universal-access",
                    "wheelchair",
                ),
            ),
            "arrows" => array(
                "title" => __("Arrows", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "angle-double-down",
                    "angle-double-left",
                    "angle-double-right",
                    "angle-double-up",
                    "angle-down",
                    "angle-left",
                    "angle-right",
                    "angle-up",
                    "arrow-alt-circle-down",
                    "arrow-alt-circle-left",
                    "arrow-alt-circle-right",
                    "arrow-alt-circle-up",
                    "arrow-circle-down",
                    "arrow-circle-left",
                    "arrow-circle-right",
                    "arrow-circle-up",
                    "arrow-down",
                    "arrow-left",
                    "arrow-right",
                    "arrow-up",
                    "arrows-alt",
                    "arrows-alt-h",
                    "arrows-alt-v",
                    "caret-down",
                    "caret-left",
                    "caret-right",
                    "caret-square-down",
                    "caret-square-left",
                    "caret-square-right",
                    "caret-square-up",
                    "caret-up",
                    "cart-arrow-down",
                    "chart-line",
                    "chevron-circle-down",
                    "chevron-circle-left",
                    "chevron-circle-right",
                    "chevron-circle-up",
                    "chevron-down",
                    "chevron-left",
                    "chevron-right",
                    "chevron-up",
                    "cloud-download-alt",
                    "cloud-upload-alt",
                    "download",
                    "exchange-alt",
                    "expand-arrows-alt",
                    "external-link-alt",
                    "external-link-square-alt",
                    "hand-point-down",
                    "hand-point-left",
                    "hand-point-right",
                    "hand-point-up",
                    "hand-pointer",
                    "history",
                    "level-down-alt",
                    "level-up-alt",
                    "location-arrow",
                    "long-arrow-alt-down",
                    "long-arrow-alt-left",
                    "long-arrow-alt-right",
                    "long-arrow-alt-up",
                    "mouse-pointer",
                    "play",
                    "random",
                    "recycle",
                    "redo",
                    "redo-alt",
                    "reply",
                    "reply-all",
                    "retweet",
                    "share",
                    "share-square",
                    "sign-in-alt",
                    "sign-out-alt",
                    "sort",
                    "sort-alpha-down",
                    "sort-alpha-up",
                    "sort-amount-down",
                    "sort-amount-up",
                    "sort-down",
                    "sort-numeric-down",
                    "sort-numeric-up",
                    "sort-up",
                    "sync",
                    "sync-alt",
                    "text-height",
                    "text-width",
                    "undo",
                    "undo-alt",
                    "upload",
                ),
            ),
            "audio-video" => array(
                "title" => __("Audio & Video", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "audio-description",
                    "backward",
                    "circle",
                    "closed-captioning",
                    "compress",
                    "eject",
                    "expand",
                    "expand-arrows-alt",
                    "fast-backward",
                    "fast-forward",
                    "file-audio",
                    "file-video",
                    "film",
                    "forward",
                    "headphones",
                    "microphone",
                    "microphone-slash",
                    "music",
                    "pause",
                    "pause-circle",
                    "phone-volume",
                    "play",
                    "play-circle",
                    "podcast",
                    "random",
                    "redo",
                    "redo-alt",
                    "rss",
                    "rss-square",
                    "step-backward",
                    "step-forward",
                    "stop",
                    "stop-circle",
                    "sync",
                    "sync-alt",
                    "undo",
                    "undo-alt",
                    "video",
                    "volume-up",
                    "volume-off",
                    "volume-down",
                    "youtube",
                ),
            ),
            "business" => array(
                "title" => __("Business", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "address-book",
                    "address-card",
                    "archive",
                    "balance-scale",
                    "birthday-cake",
                    "book",
                    "building",
                    "bullseye",
                    "bullhorn",
                    "briefcase",
                    "calculator",
                    "calendar",
                    "calendar-alt",
                    "certificate",
                    "chart-area",
                    "chart-bar",
                    "chart-line",
                    "chart-pie",
                    "clipboard",
                    "coffee",
                    "columns",
                    "compass",
                    "copy",
                    "copyright",
                    "cut",
                    "edit",
                    "envelope",
                    "envelope-open",
                    "envelope-square",
                    "eraser",
                    "fax",
                    "file",
                    "file-alt",
                    "folder",
                    "folder-open",
                    "globe",
                    "industry",
                    "paperclip",
                    "paste",
                    "pen-square",
                    "pencil-alt",
                    "percent",
                    "phone",
                    "phone-slash",
                    "phone-square",
                    "phone-volume",
                    "registered",
                    "save",
                    "sitemap",
                    "sticky-note",
                    "suitcase",
                    "table",
                    "tag",
                    "tags",
                    "tasks",
                    "thumbtack",
                    "trademark",
                ),
            ),
            "charity" => array(
                "title" => __("Charity", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "dollar-sign",
                    "donate",
                    "dove",
                    "gift",
                    "globe",
                    "hand-holding-heart",
                    "hand-holding-usd",
                    "hands-helping",
                    "handshake",
                    "heart",
                    "leaf",
                    "parachute-box",
                    "piggy-bank",
                    "ribbon",
                    "seedling",
                ),
            ),
            "chat" => array(
                "title" => __("Chat", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "comment",
                    "comment-alt",
                    "comment-dots",
                    "comment-slash",
                    "comments",
                    "phone",
                    "phone-slash",
                    "poo",
                    "quote-left",
                    "quote-right",
                    "smile",
                    "video",
                    "video-slash",
                    "meh",
                    "frown",
                ),
            ),
            "chess" => array(
                "title" => __("Chess", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "chess",
                    "chess-king",
                    "chess-queen",
                    "chess-bishop",
                    "chess-knight",
                    "chess-rook",
                    "chess-pawn",
                    "chess-board",
                    "square-full",
                ),
            ),
            "code" => array(
                "title" => __("Code", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "archive",
                    "barcode",
                    "bath",
                    "bug",
                    "code",
                    "code-branch",
                    "coffee",
                    "file",
                    "file-alt",
                    "file-code",
                    "fire-extinguisher",
                    "folder",
                    "folder-open",
                    "filter",
                    "keyboard",
                    "microchip",
                    "qrcode",
                    "shield-alt",
                    "sitemap",
                    "terminal",
                    "user-secret",
                    "window-close",
                    "window-maximize",
                    "window-minimize",
                    "window-restore",
                ),
            ),
            "communication" => array(
                "title" => __("Communication", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "address-book",
                    "address-card",
                    "american-sign-language-interpreting",
                    "assistive-listening-systems",
                    "at",
                    "bell",
                    "bell-slash",
                    "bluetooth",
                    "bluetooth-b",
                    "bullhorn",
                    "comment",
                    "comment-alt",
                    "comments",
                    "envelope",
                    "envelope-open",
                    "envelope-square",
                    "fax",
                    "inbox",
                    "language",
                    "microphone",
                    "microphone-slash",
                    "mobile",
                    "mobile-alt",
                    "paper-plane",
                    "phone",
                    "phone-slash",
                    "phone-square",
                    "phone-volume",
                    "rss",
                    "rss-square",
                    "tty",
                    "wifi",
                ),
            ),
            "computers" => array(
                "title" => __("Computers", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "database",
                    "desktop",
                    "download",
                    "headphones",
                    "hdd",
                    "keyboard",
                    "laptop",
                    "microchip",
                    "mobile",
                    "mobile-alt",
                    "plug",
                    "power-off",
                    "print",
                    "save",
                    "server",
                    "tablet",
                    "tablet-alt",
                    "tv",
                    "upload",
                ),
            ),
            "currency" => array(
                "title" => __("Currency", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "btc",
                    "bitcoin",
                    "dollar-sign",
                    "euro-sign",
                    "gg",
                    "gg-circle",
                    "lira-sign",
                    "money-bill-alt",
                    "pound-sign",
                    "ruble-sign",
                    "rupee-sign",
                    "shekel-sign",
                    "won-sign",
                    "yen-sign",
                ),
            ),
            "date-time" => array(
                "title" => __("Date & Time", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "bell",
                    "bell-slash",
                    "calendar",
                    "calendar-alt",
                    "calendar-check",
                    "calendar-minus",
                    "calendar-plus",
                    "calendar-times",
                    "clock",
                    "hourglass",
                    "hourglass-end",
                    "hourglass-half",
                    "hourglass-start",
                    "stopwatch",
                ),
            ),
            "design" => array(
                "title" => __("Design", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "adjust",
                    "clone",
                    "copy",
                    "crop",
                    "crosshairs",
                    "cut",
                    "edit",
                    "eraser",
                    "eye",
                    "eye-dropper",
                    "eye-slash",
                    "object-group",
                    "object-ungroup",
                    "paint-brush",
                    "paste",
                    "pencil-alt",
                    "save",
                    "tint",
                ),
            ),
            "editors" => array(
                "title" => __("Editors", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "align-center",
                    "align-justify",
                    "align-left",
                    "align-right",
                    "bold",
                    "clipboard",
                    "clone",
                    "columns",
                    "copy",
                    "cut",
                    "edit",
                    "eraser",
                    "file",
                    "file-alt",
                    "font",
                    "heading",
                    "i-cursor",
                    "indent",
                    "italic",
                    "link",
                    "list",
                    "list-alt",
                    "list-ol",
                    "list-ul",
                    "outdent",
                    "paper-plane",
                    "paperclip",
                    "paragraph",
                    "paste",
                    "pencil-alt",
                    "print",
                    "quote-left",
                    "quote-right",
                    "redo",
                    "redo-alt",
                    "reply",
                    "reply-all",
                    "share",
                    "strikethrough",
                    "subscript",
                    "superscript",
                    "sync",
                    "sync-alt",
                    "table",
                    "tasks",
                    "text-height",
                    "text-width",
                    "th",
                    "th-large",
                    "th-list",
                    "trash",
                    "trash-alt",
                    "underline",
                    "undo",
                    "undo-alt",
                    "unlink",
                ),
            ),
            "files" => array(
                "title" => __("Files", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "archive",
                    "clone",
                    "copy",
                    "cut",
                    "file",
                    "file-alt",
                    "file-archive",
                    "file-audio",
                    "file-code",
                    "file-excel",
                    "file-image",
                    "file-pdf",
                    "file-powerpoint",
                    "file-video",
                    "file-word",
                    "folder",
                    "folder-open",
                    "paste",
                    "save",
                    "sticky-note",
                ),
            ),
            "gender" => array(
                "title" => __("Genders", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "genderless",
                    "mars",
                    "mars-double",
                    "mars-stroke",
                    "mars-stroke-h",
                    "mars-stroke-v",
                    "mercury",
                    "neuter",
                    "transgender",
                    "transgender-alt",
                    "venus",
                    "venus-double",
                    "venus-mars",
                ),
            ),
            "hands" => array(
                "title" => __("Hands", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "hand-lizard",
                    "hand-paper",
                    "hand-peace",
                    "hand-point-down",
                    "hand-point-left",
                    "hand-point-right",
                    "hand-point-up",
                    "hand-pointer",
                    "hand-rock",
                    "hand-scissors",
                    "hand-spock",
                    "handshake",
                    "thumbs-down",
                    "thumbs-up",
                    "hand-holding",
                    "hands",
                    "allergies",
                ),
            ),
            "health" => array(
                "title" => __("Health", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "accessible-icon",
                    "ambulance",
                    "h-square",
                    "heart",
                    "heartbeat",
                    "hospital",
                    "medkit",
                    "plus-square",
                    "stethoscope",
                    "user-md",
                    "wheelchair",
                ),
            ),
            "images" => array(
                "title" => __("Images", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "adjust",
                    "bolt",
                    "camera",
                    "camera-retro",
                    "clone",
                    "compress",
                    "eye",
                    "eye-dropper",
                    "eye-slash",
                    "expand",
                    "file-image",
                    "film",
                    "id-badge",
                    "id-card",
                    "image",
                    "images",
                    "portrait",
                    "sliders-h",
                    "tint",
                ),
            ),
            "interfaces" => array(
                "title" => __("Interfaces", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "ban",
                    "barcode",
                    "bars",
                    "beer",
                    "bell",
                    "bell-slash",
                    "bug",
                    "bullhorn",
                    "bullseye",
                    "calculator",
                    "calendar",
                    "calendar-alt",
                    "calendar-check",
                    "calendar-minus",
                    "calendar-plus",
                    "calendar-times",
                    "certificate",
                    "check",
                    "check-circle",
                    "check-square",
                    "circle",
                    "clipboard",
                    "clone",
                    "cloud",
                    "cloud-download-alt",
                    "cloud-upload-alt",
                    "coffee",
                    "cog",
                    "cogs",
                    "copy",
                    "cut",
                    "database",
                    "dot-circle",
                    "download",
                    "edit",
                    "ellipsis-h",
                    "ellipsis-v",
                    "envelope",
                    "envelope-open",
                    "eraser",
                    "exclamation",
                    "exclamation-circle",
                    "exclamation-triangle",
                    "external-link-alt",
                    "external-link-square-alt",
                    "eye",
                    "eye-slash",
                    "file",
                    "file-alt",
                    "filter",
                    "flag",
                    "flag-checkered",
                    "folder",
                    "folder-open",
                    "frown",
                    "hashtag",
                    "heart",
                    "history",
                    "home",
                    "i-cursor",
                    "info",
                    "info-circle",
                    "language",
                    "magic",
                    "meh",
                    "microphone",
                    "microphone-slash",
                    "minus",
                    "minus-circle",
                    "minus-square",
                    "paste",
                    "pencil-alt",
                    "plus",
                    "plus-circle",
                    "plus-square",
                    "poo",
                    "qrcode",
                    "question",
                    "question-circle",
                    "quote-left",
                    "quote-right",
                    "redo",
                    "redo-alt",
                    "reply",
                    "reply-all",
                    "rss",
                    "rss-square",
                    "save",
                    "search",
                    "search-minus",
                    "search-plus",
                    "share",
                    "share-alt",
                    "share-alt-square",
                    "share-square",
                    "shield-alt",
                    "sign-in-alt",
                    "sign-out-alt",
                    "signal",
                    "sitemap",
                    "sliders-h",
                    "sort",
                    "sort-alpha-down",
                    "sort-alpha-up",
                    "sort-amount-down",
                    "sort-amount-up",
                    "sort-down",
                    "sort-numeric-down",
                    "sort-numeric-up",
                    "sort-up",
                    "smile",
                    "star",
                    "star-half",
                    "sync",
                    "sync-alt",
                    "thumbs-down",
                    "thumbs-up",
                    "times",
                    "times-circle",
                    "toggle-off",
                    "toggle-on",
                    "trash",
                    "trash-alt",
                    "trophy",
                    "undo",
                    "undo-alt",
                    "upload",
                    "user",
                    "user-alt",
                    "user-circle",
                    "wifi",
                ),
            ),
            "logistics" => array(
                "title" => __("Logistics", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "truck",
                    "shipping-fast",
                    "dolly",
                    "dolly-flatbed",
                    "pallet",
                    "boxes",
                    "box",
                    "warehouse",
                    "clipboard-list",
                    "clipboard-check",
                ),
            ),
            "maps" => array(
                "title" => __("Maps", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "ambulance",
                    "anchor",
                    "balance-scale",
                    "bath",
                    "bed",
                    "beer",
                    "bell",
                    "bell-slash",
                    "bicycle",
                    "binoculars",
                    "birthday-cake",
                    "blind",
                    "bomb",
                    "book",
                    "bookmark",
                    "briefcase",
                    "building",
                    "car",
                    "coffee",
                    "crosshairs",
                    "dollar-sign",
                    "eye",
                    "eye-slash",
                    "fighter-jet",
                    "fire",
                    "fire-extinguisher",
                    "flag",
                    "flag-checkered",
                    "flask",
                    "gamepad",
                    "gavel",
                    "gift",
                    "glass-martini",
                    "globe",
                    "graduation-cap",
                    "h-square",
                    "heart",
                    "heartbeat",
                    "home",
                    "hospital",
                    "image",
                    "images",
                    "industry",
                    "info",
                    "info-circle",
                    "key",
                    "leaf",
                    "lemon",
                    "life-ring",
                    "lightbulb",
                    "location-arrow",
                    "low-vision",
                    "magnet",
                    "male",
                    "map",
                    "map-marker",
                    "map-marker-alt",
                    "map-pin",
                    "map-signs",
                    "medkit",
                    "money-bill-alt",
                    "motorcycle",
                    "music",
                    "newspaper",
                    "paw",
                    "phone",
                    "phone-square",
                    "phone-volume",
                    "plane",
                    "plug",
                    "plus",
                    "plus-square",
                    "print",
                    "recycle",
                    "road",
                    "rocket",
                    "search",
                    "search-minus",
                    "search-plus",
                    "ship",
                    "shopping-bag",
                    "shopping-basket",
                    "shopping-cart",
                    "shower",
                    "street-view",
                    "subway",
                    "suitcase",
                    "tag",
                    "tags",
                    "taxi",
                    "thumbtack",
                    "ticket-alt",
                    "tint",
                    "train",
                    "tree",
                    "trophy",
                    "truck",
                    "tty",
                    "umbrella",
                    "university",
                    "utensil-spoon",
                    "utensils",
                    "wine-glass",
                    "wheelchair",
                    "wifi",
                    "wrench",
                ),
            ),
            "medical" => array(
                "title" => __("Medical", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "allergies",
                    "ambulance",
                    "band-aid",
                    "briefcase-medical",
                    "burn",
                    "capsules",
                    "diagnoses",
                    "dna",
                    "file-medical",
                    "file-medical-alt",
                    "first-aid",
                    "heart",
                    "heartbeat",
                    "hospital",
                    "hospital-alt",
                    "hospital-symbol",
                    "id-card-alt",
                    "notes-medical",
                    "pills",
                    "plus",
                    "prescription-bottle",
                    "prescription-bottle-alt",
                    "procedures",
                    "smoking",
                    "stethoscope",
                    "syringe",
                    "tablets",
                    "thermometer",
                    "user-md",
                    "vial",
                    "vials",
                    "weight",
                    "x-ray",
                ),
            ),
            "moving" => array(
                "title" => __("Moving", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "truck-moving",
                    "truck-loading",
                    "tape",
                    "box-open",
                    "sign",
                    "couch",
                    "people-carry",
                    "dolly",
                    "wine-glass",
                    "suitcase",
                    "archive",
                ),
            ),
            "objects" => array(
                "title" => __("Objects", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "ambulance",
                    "anchor",
                    "archive",
                    "balance-scale",
                    "bath",
                    "bed",
                    "beer",
                    "bell",
                    "bicycle",
                    "binoculars",
                    "birthday-cake",
                    "bomb",
                    "book",
                    "bookmark",
                    "briefcase",
                    "bug",
                    "building",
                    "bullhorn",
                    "bullseye",
                    "bus",
                    "calculator",
                    "calendar",
                    "calendar-alt",
                    "camera",
                    "camera-retro",
                    "car",
                    "clipboard",
                    "cloud",
                    "coffee",
                    "cog",
                    "cogs",
                    "compass",
                    "copy",
                    "cube",
                    "cubes",
                    "cut",
                    "envelope",
                    "envelope-open",
                    "eraser",
                    "eye",
                    "eye-dropper",
                    "fax",
                    "fighter-jet",
                    "file",
                    "file-alt",
                    "film",
                    "fire",
                    "fire-extinguisher",
                    "flag",
                    "flag-checkered",
                    "flask",
                    "futbol",
                    "gamepad",
                    "gavel",
                    "gem",
                    "gift",
                    "glass-martini",
                    "globe",
                    "graduation-cap",
                    "hdd",
                    "headphones",
                    "heart",
                    "home",
                    "hospital",
                    "hourglass",
                    "image",
                    "images",
                    "industry",
                    "key",
                    "keyboard",
                    "laptop",
                    "leaf",
                    "lemon",
                    "life-ring",
                    "lightbulb",
                    "lock",
                    "lock-open",
                    "magic",
                    "magnet",
                    "map",
                    "map-marker",
                    "map-marker-alt",
                    "map-pin",
                    "map-signs",
                    "medkit",
                    "microchip",
                    "microphone",
                    "mobile",
                    "mobile-alt",
                    "money-bill-alt",
                    "moon",
                    "motorcycle",
                    "newspaper",
                    "paint-brush",
                    "paper-plane",
                    "paperclip",
                    "paste",
                    "paw",
                    "pencil-alt",
                    "phone",
                    "plane",
                    "plug",
                    "print",
                    "puzzle-piece",
                    "road",
                    "rocket",
                    "save",
                    "search",
                    "shield-alt",
                    "shopping-bag",
                    "shopping-basket",
                    "shopping-cart",
                    "shower",
                    "snowflake",
                    "space-shuttle",
                    "star",
                    "sticky-note",
                    "stopwatch",
                    "subway",
                    "suitcase",
                    "sun",
                    "tablet",
                    "tablet-alt",
                    "tachometer-alt",
                    "tag",
                    "tags",
                    "taxi",
                    "thumbtack",
                    "ticket-alt",
                    "train",
                    "trash",
                    "trash-alt",
                    "tree",
                    "trophy",
                    "truck",
                    "tv",
                    "umbrella",
                    "university",
                    "unlock",
                    "unlock-alt",
                    "utensil-spoon",
                    "utensils",
                    "wheelchair",
                    "wine-glass",
                    "wrench",
                ),
            ),
            "payments-shopping" => array(
                "title" => __("Payments & Shopping", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "amazon-pay",
                    "apple-pay",
                    "bell",
                    "bookmark",
                    "bullhorn",
                    "camera",
                    "camera-retro",
                    "cart-arrow-down",
                    "cart-plus",
                    "certificate",
                    "cc-amazon-pay",
                    "cc-amex",
                    "cc-apple-pay",
                    "cc-diners-club",
                    "cc-discover",
                    "cc-jcb",
                    "cc-mastercard",
                    "cc-paypal",
                    "cc-stripe",
                    "cc-visa",
                    "credit-card",
                    "ethereum",
                    "gem",
                    "gift",
                    "google-wallet",
                    "handshake",
                    "heart",
                    "key",
                    "paypal",
                    "shopping-bag",
                    "shopping-basket",
                    "shopping-cart",
                    "star",
                    "stripe",
                    "stripe-s",
                    "tag",
                    "tags",
                    "thumbs-down",
                    "thumbs-up",
                    "trophy",
                ),
            ),
            "shapes" => array(
                "title" => __("Shapes", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "bookmark",
                    "calendar",
                    "certificate",
                    "circle",
                    "cloud",
                    "comment",
                    "file",
                    "folder",
                    "heart",
                    "map-marker",
                    "play",
                    "square",
                    "star",
                ),
            ),
            "spinners" => array(
                "title" => __("Spinners", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "asterisk",
                    "certificate",
                    "circle-notch",
                    "cog",
                    "compass",
                    "crosshairs",
                    "life-ring",
                    "snowflake",
                    "spinner",
                    "sun",
                    "sync",
                ),
            ),
            "sports" => array(
                "title" => __("Sports", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "baseball-ball",
                    "basketball-ball",
                    "bowling-ball",
                    "football-ball",
                    "futbol",
                    "golf-ball",
                    "hockey-puck",
                    "quidditch",
                    "table-tennis",
                    "volleyball-ball",
                ),
            ),
            "status" => array(
                "title" => __("Status", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "ban",
                    "battery-empty",
                    "battery-full",
                    "battery-half",
                    "battery-quarter",
                    "battery-three-quarters",
                    "bell",
                    "bell-slash",
                    "calendar",
                    "calendar-alt",
                    "calendar-check",
                    "calendar-minus",
                    "calendar-plus",
                    "calendar-times",
                    "cart-arrow-down",
                    "cart-plus",
                    "exclamation",
                    "exclamation-circle",
                    "exclamation-triangle",
                    "eye",
                    "eye-slash",
                    "file",
                    "file-alt",
                    "folder",
                    "folder-open",
                    "info",
                    "info-circle",
                    "lock",
                    "lock-open",
                    "minus",
                    "minus-circle",
                    "minus-square",
                    "plus",
                    "plus-circle",
                    "plus-square",
                    "question",
                    "question-circle",
                    "shield-alt",
                    "sign-in-alt",
                    "sign-out-alt",
                    "shopping-cart",
                    "thermometer-empty",
                    "thermometer-full",
                    "thermometer-half",
                    "thermometer-quarter",
                    "thermometer-three-quarters",
                    "thumbs-down",
                    "thumbs-up",
                    "toggle-off",
                    "toggle-on",
                    "unlock",
                    "unlock-alt",
                ),
            ),
            "users-people" => array(
                "title" => __("Users & People", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "accessible-icon",
                    "address-book",
                    "address-card",
                    "bed",
                    "blind",
                    "child",
                    "female",
                    "frown",
                    "id-badge",
                    "id-card",
                    "id-card-alt",
                    "male",
                    "meh",
                    "poo",
                    "portrait",
                    "power-off",
                    "smile",
                    "street-view",
                    "user",
                    "user-alt",
                    "user-circle",
                    "user-md",
                    "user-plus",
                    "user-secret",
                    "user-times",
                    "users",
                    "user-astronaut",
                    "user-check",
                    "user-clock",
                    "user-cog",
                    "user-edit",
                    "user-friends",
                    "user-graduate",
                    "user-lock",
                    "user-minus",
                    "user-ninja",
                    "user-shield",
                    "user-slash",
                    "user-tag",
                    "user-tie",
                    "user-alt-slash",
                    "wheelchair",
                ),
            ),
            "vehicles" => array(
                "title" => __("Vehicles", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "accessible-icon",
                    "ambulance",
                    "bicycle",
                    "bus",
                    "car",
                    "fighter-jet",
                    "motorcycle",
                    "paper-plane",
                    "plane",
                    "rocket",
                    "ship",
                    "shopping-cart",
                    "space-shuttle",
                    "subway",
                    "taxi",
                    "train",
                    "truck",
                    "wheelchair",
                ),
            ),
            "writing" => array(
                "title" => __("Writing", __FILE__),
                "prefix" => "fab fa-",
                "icons" => array(
                    "archive",
                    "book",
                    "bookmark",
                    "edit",
                    "envelope",
                    "envelope-open",
                    "eraser",
                    "file",
                    "file-alt",
                    "folder",
                    "folder-open",
                    "keyboard",
                    "newspaper",
                    "paper-plane",
                    "paperclip",
                    "paragraph",
                    "pen-square",
                    "pencil-alt",
                    "quote-left",
                    "quote-right",
                    "sticky-note",
                    "thumbtack",
                ),
            ),
        )
    );

    return $icons;
}